# Generated by Django 2.1.7 on 2019-02-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190221_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('cloud', models.CharField(max_length=20)),
                ('api_id', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=50)),
            ],
        ),
    ]
