# Generated by Django 2.1.7 on 2019-03-01 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('method', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('manager', models.CharField(max_length=50)),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.client')),
            ],
        ),
    ]
